name: PR

on:
  pull_request:
    branches: [ "master" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Wilgnne.Agenda.sln
    - name: Build
      run: dotnet build Wilgnne.Agenda.sln --no-restore
    - name: Test
      run: dotnet test Wilgnne.Agenda.Application.Tests --no-build --verbosity normal

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install --frozen-lockfile
    - run: yarn build
